project_id = "afsyxzxwxszujnsmukff"

[functions.timestamped-lyrics]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.suno]
verify_jwt = false

[functions.generate-album-cover]
verify_jwt = false

[functions.generate-artist-image]
verify_jwt = false

[functions.analyze-face]
verify_jwt = false
